apiVersion: piraeus.io/v1
kind: LinstorSatelliteConfiguration
metadata:
  name: storage-pool
spec:
  storagePools:
    - name: talos-lvm-pool
      lvmPool:
        volumeGroup: talos-vg
      source:
        hostDevices:
          - /dev/sdb