---
apiVersion: v1
kind: Namespace
metadata:
  name: piraeus-datastore
  labels:
    toolkit.fluxcd.io/tenant: devops-team
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: piraeus-operator
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    tag: v2.6.0
  url: https://github.com/piraeusdatastore/piraeus-operator
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: piraeus-operator
  namespace: flux-system
spec:
  interval: 10m
  path: ./config/default
  prune: true
  sourceRef:
    kind: GitRepository
    name: piraeus-operator
  targetNamespace: piraeus-datastore